### ISSUE TITLE
[Linker Error] ld: library not found for -lSocialQQ

### ISSUE THREAD

**Issue by zhangwebb** [sparkdreamstudio/rn-umeng-share#3]
按照步骤添加，编译报：

> ld: library not found for -lSocialQQ
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

`Framework Search Paths` 路径：

> $(SRCROOT)/../node_modules/rn-umeng-share/ios/RCTUmengShare/UmengSocial/UMSocial_Sdk_Extra_Frameworks/TencentOpenAPI

已添加，并且存在`libSocialQQ.a`啊？还可能是哪里的问题？

**Comment by sparkdreamstudio** [comment]
@zhangwebb 是umengshare项目报错还是自己的项目报错，试试再自己的项目中删掉libsocialqq和其他.a文件，我应该readme写的有问题

**Comment by zhangwebb** [comment]
删掉也不行，是在编译自己的项目时报的错误，就那关键的一个
